name: Actualizar Agenda Automáticamente

on:
  schedule:
    - cron: '0 * * * *' # Corre cada 1 hora
  workflow_dispatch: # Permite probar a mano

jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar librerías de scraping
      run: pip install beautifulsoup4 requests

    - name: Ejecutar el Scraper para armar el HTML
      run: python fpt.py

    - name: Desplegar directamente a Netlify
      uses: SouthAtari/deploy-netlify-action@v1.1.4
      with:
        path: './'
        netlify_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        site_id: ${{ secrets.NETLIFY_SITE_ID }}
